{% set version = "0.0-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rebus.numbers
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rebus.numbers_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rebus.numbers/rebus.numbers_{{ version }}.tar.gz
  sha256: 43da0fcf06576ef146cf9d363a087ac74fe918f0394d695822920804fed72f37

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1005
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-rebus.base
  run:
    - r-base
    - r-rebus.base

test:
  commands:
    - $R -e "library('rebus.numbers')"           # [not win]
    - "\"%R%\" -e \"library('rebus.numbers')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rebus.numbers
  license: Unlimited
  summary: Build regular expressions piece by piece using human readable code. This package contains number-related functionality, and is primarily intended to be used by package developers.
  license_family: Other
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
